
import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { UploadCloud, Zap, BookCopy, Brain, Mic, HelpCircle, PlayCircle } from 'lucide-react';

const featureVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: (i) => ({
    opacity: 1,
    y: 0,
    transition: {
      delay: i * 0.1,
      duration: 0.5,
    },
  }),
};

const HomePage = () => {
  const features = [
    {
      icon: <Zap className="h-10 w-10 text-primary mb-4" />,
      title: "AI Summarization",
      description: "Get concise summaries and relevant question-answer pairs generated by powerful AI models.",
      imgPlaceholder: "Abstract representation of AI processing text into summaries and questions",
      link: "/summarize"
    },
    {
      icon: <PlayCircle className="h-10 w-10 text-primary mb-4" />,
      title: "Audio Lecture Generation",
      description: "Convert lecture content into natural-sounding audio for learning on the go.",
      imgPlaceholder: "Sound wave icon transforming into a play button",
      link: "/text-to-speech"
    },
    {
      icon: <HelpCircle className="h-10 w-10 text-primary mb-4" />,
      title: "Generate QA",
      description: "Test your knowledge with engaging quizzes generated from your lecture material.",
      imgPlaceholder: "Quiz icon with checkmarks and question marks",
      link: "generate-qa"
    }
    ,{
      icon: <BookCopy className="h-10 w-10 text-primary mb-4" />,
      title: "PDF OCR",
      description: "Extract text from scanned PDF documents using advanced Optical Character Recognition (OCR).",
      imgPlaceholder: "Icon of a book opening with a calendar, symbolizing spaced repetition",
      link: "pdf-ocr"
    },
    // {
    //   icon: <HelpCircle className="h-10 w-10 text-primary mb-4" />,
    //   title: "Interactive Quizzes",
    //   description: "Test your knowledge with engaging quizzes generated from your lecture material.",
    //   imgPlaceholder: "Quiz icon with checkmarks and question marks"      
    // },
    {
      icon: <Brain className="h-10 w-10 text-primary mb-4" />,
      title: "Personalized Learning",
      description: "The system adapts to your progress, offering a customized learning journey.",
      imgPlaceholder: "Stylized brain icon with interconnected nodes, representing personalized learning paths",
      link: "roadmap"
    },
  ];

  return (
    <div className="flex flex-col items-center">
      <motion.section
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.7, ease: "easeOut" }}
        className="text-center py-16 md:py-24"
      >
        <motion.div
          className="absolute inset-0 overflow-hidden -z-10"
          initial={{ opacity: 0 }}
          animate={{ opacity: 0.5 }}
          transition={{ duration: 1, delay: 0.5 }}
        >
          <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-500 rounded-full filter blur-3xl opacity-30 animate-pulse-glow"></div>
          <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-pink-500 rounded-full filter blur-3xl opacity-30 animate-pulse-glow animation-delay-2000"></div>
        </motion.div>

        <h1 className="text-5xl md:text-7xl font-extrabold mb-6 tracking-tight">
          <span className="bg-clip-text text-transparent bg-gradient-to-r from-primary via-accent to-pink-500">
            Unlock Your Lecture Potential
          </span>
        </h1>
        <p className="text-xl md:text-2xl text-muted-foreground mb-10 max-w-3xl mx-auto">
          Transform your study sessions with our AI-Powered Lecture Assistant. Upload, learn, and master your course material like never before.
        </p>
        <motion.div
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        >
          <Link to="/summarize">
            <Button size="lg" className="text-lg px-8 py-6 bg-primary hover:bg-primary/90 shadow-lg shadow-primary/30 transition-all duration-300 ease-in-out transform hover:-translate-y-1">
              Get Started Now
              <UploadCloud className="ml-2 h-5 w-5" />
            </Button>
          </Link>
        </motion.div>
        <div className="mt-12">
          <img class="w-full max-w-3xl mx-auto rounded-lg shadow-2xl" alt="AI Lecture Assistant dashboard preview" src="https://images.unsplash.com/photo-1624388611710-bdf95023d1c2" />
        </div>
      </motion.section>

      <motion.section
        className="py-16 md:py-24 w-full"
        initial="hidden"
        animate="visible"
      >
        <h2 className="text-4xl font-bold text-center mb-16">
          Powerful Features, Effortless Learning
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <motion.div key={index} custom={index} variants={featureVariants}>
              <Card className="h-full flex flex-col glassmorphic-card hover:shadow-primary/30 transition-shadow duration-300">
                <CardHeader className="items-center text-center">
                  {feature.icon}
                  <CardTitle className="text-2xl">{feature.title}</CardTitle>
                </CardHeader>
                <CardContent className="flex-grow text-center">
                  <CardDescription className="text-base text-muted-foreground">
                    {feature.description}
                  </CardDescription>
                </CardContent>
                <div className="p-6 pt-0 text-center">
                  <Link to={feature.link}>
                    <Button variant="outline" className="border-primary text-primary hover:bg-primary/10">
                      Learn More</Button>
                  </Link>

                </div>
              </Card>
            </motion.div>
          ))}
        </div>
      </motion.section>

      <motion.section
        className="py-16 md:py-24 w-full text-center bg-background/50 rounded-lg shadow-inner my-12"
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true, amount: 0.3 }}
        transition={{ duration: 0.8 }}
      >
        <h2 className="text-4xl font-bold mb-6">Ready to Revolutionize Your Studies?</h2>
        <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
          Join thousands of students who are already acing their exams with smarter study tools.
        </p>
        <motion.div
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        >
          <Link to="/summarize">
            <Button size="lg" className="text-lg px-10 py-7 bg-gradient-to-r from-accent to-pink-500 hover:from-pink-500 hover:to-accent text-primary-foreground shadow-lg shadow-pink-500/40 transition-all duration-300 ease-in-out transform hover:-translate-y-1">
              Start Learning Smarter Today!
            </Button>
          </Link>
        </motion.div>
      </motion.section>
    </div>
  );
};

export default HomePage;
